# Generated by Django 3.1.1 on 2020-09-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(max_length=100)),
                ('insurance_start_date', models.DateField()),
                ('insurance_end_date', models.DateField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
